#!/usr/bin/env node
/**
 * Reads the glyph widths of the carousel fonts (assets/fonts/*.woff) and writes src/lib/carouselMetrics.ts.
 * The slide fitter uses them to estimate how tall a slide's text will be before it is drawn, so text that would run off
 * the bottom is made smaller. Run it again only if a font file changes:
 *
 *   node scripts/font-metrics.mjs
 *
 * No dependencies: a .woff is an sfnt font with each table deflated, so Node's zlib reads it directly.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { inflateSync } from "node:zlib";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const FONTS = {
  bricolage: "BricolageGrotesque-ExtraBold.woff",
  dmSans: "DMSans-Regular.woff",
  dmSansMedium: "DMSans-Medium.woff",
  dmSansItalic: "DMSans-Italic.woff",
  dmMono: "DMMono-Medium.woff",
};

/** The characters the table covers: printable ASCII plus the typographic marks a model likes to write. */
const EXTRA = "‘’“”–—…×→•·€£₹°±≈≥≤✓";
const CHARS = [...Array(95)].map((_, i) => String.fromCharCode(32 + i)).concat([...EXTRA]);

function readWoff(buffer) {
  if (buffer.toString("latin1", 0, 4) !== "wOFF") throw new Error("not a WOFF file");
  const numTables = buffer.readUInt16BE(12);
  const tables = {};
  for (let i = 0; i < numTables; i += 1) {
    const at = 44 + i * 20;
    const tag = buffer.toString("latin1", at, at + 4);
    const offset = buffer.readUInt32BE(at + 4);
    const compLength = buffer.readUInt32BE(at + 8);
    const origLength = buffer.readUInt32BE(at + 12);
    const raw = buffer.subarray(offset, offset + compLength);
    tables[tag] = compLength < origLength ? inflateSync(raw) : raw;
  }
  return tables;
}

/** codepoint -> glyph id, from the first usable Unicode cmap subtable (format 4 or 12). */
function readCmap(cmap) {
  const count = cmap.readUInt16BE(2);
  const map = new Map();
  for (let i = 0; i < count; i += 1) {
    const platform = cmap.readUInt16BE(4 + i * 8);
    const encoding = cmap.readUInt16BE(6 + i * 8);
    const offset = cmap.readUInt32BE(8 + i * 8);
    const unicode = platform === 0 || (platform === 3 && (encoding === 1 || encoding === 10));
    if (!unicode) continue;
    const format = cmap.readUInt16BE(offset);
    if (format === 4) {
      const segX2 = cmap.readUInt16BE(offset + 6);
      const ends = offset + 14;
      const starts = ends + segX2 + 2;
      const deltas = starts + segX2;
      const ranges = deltas + segX2;
      for (let s = 0; s < segX2 / 2; s += 1) {
        const end = cmap.readUInt16BE(ends + s * 2);
        const start = cmap.readUInt16BE(starts + s * 2);
        const delta = cmap.readInt16BE(deltas + s * 2);
        const rangeOffset = cmap.readUInt16BE(ranges + s * 2);
        for (let c = start; c <= end && c !== 0xffff; c += 1) {
          let gid;
          if (rangeOffset === 0) gid = (c + delta) & 0xffff;
          else {
            const at = ranges + s * 2 + rangeOffset + (c - start) * 2;
            const g = cmap.readUInt16BE(at);
            gid = g === 0 ? 0 : (g + delta) & 0xffff;
          }
          if (gid) map.set(c, gid);
        }
      }
    } else if (format === 12) {
      const groups = cmap.readUInt32BE(offset + 12);
      for (let g = 0; g < groups; g += 1) {
        const at = offset + 16 + g * 12;
        const start = cmap.readUInt32BE(at);
        const end = cmap.readUInt32BE(at + 4);
        const gid0 = cmap.readUInt32BE(at + 8);
        for (let c = start; c <= end; c += 1) map.set(c, gid0 + (c - start));
      }
    }
    if (map.size > 0) return map;
  }
  throw new Error("no Unicode cmap");
}

function measure(file) {
  const t = readWoff(readFileSync(join(root, "assets", "fonts", file)));
  const unitsPerEm = t.head.readUInt16BE(18);
  const numberOfHMetrics = t.hhea.readUInt16BE(34);
  const cmap = readCmap(t.cmap);
  const advance = (gid) => t.hmtx.readUInt16BE(4 * Math.min(gid, numberOfHMetrics - 1));
  const widths = {};
  let sum = 0;
  let n = 0;
  for (const ch of CHARS) {
    const gid = cmap.get(ch.codePointAt(0));
    if (gid === undefined) continue;
    widths[ch] = advance(gid);
    if (ch.charCodeAt(0) < 127) {
      sum += widths[ch];
      n += 1;
    }
  }
  return { unitsPerEm, fallback: Math.round(sum / n), widths };
}

let out = `// GENERATED by scripts/font-metrics.mjs from assets/fonts/*.woff. Do not edit by hand.
// Glyph advance widths in font units, used to estimate how tall a slide's text will be (src/lib/carouselFit.ts).

export interface FontMetrics {
  unitsPerEm: number;
  /** The width used for a character the table does not list (the ASCII average). */
  fallback: number;
  widths: Record<string, number>;
}

const DATA = {
`;
for (const [name, file] of Object.entries(FONTS)) {
  const m = measure(file);
  out += `  ${name}: ${JSON.stringify(m)},\n`;
}
out += `} satisfies Record<string, FontMetrics>;

export type FontName = keyof typeof DATA;

/** Widths by font name, typed so a character can be looked up by any string. */
export const METRICS: Record<FontName, FontMetrics> = DATA;
`;
writeFileSync(join(root, "src", "lib", "carouselMetrics.ts"), out);
console.log("wrote src/lib/carouselMetrics.ts");
